#VALEURS POSSIBLES DE LA VARIABLE Mode
HMI_Mode_Off = 0xA0
HMI_Mode_Auto = 0xA1
HMI_Mode_Program = 0xA2
HMI_Mode_Hollidays = 0xA3

#VALEURS POSSIBLES DE LA VARIABLE CouleurTempo
Tempo_Bleu = 1
Tempo_Blanc = 2
Tempo_Rouge = 3
Tempo_NoConnection = 0

# COULEURS POUR BACKGROUND
COLOUR_FRAME = '#C0C0C0'
COLOUR_BLUE = '#4065DE'
COLOUR_WHITE = '#FFFFFF'
COLOUR_RED = '#FF0000'



